language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - sources
rvm:
- 2.4
env:
  global:
  - secure: "EvXp01+Jf7b5Yrvhw8SrWZ0Bj/7F1vJg3/utVY0b6hyT2I4y+Ey6M7i3Xf3hyGFhjvHATBoKDQKrGJCsJd+YnzS2KNGHytEd1d0NafdvTBgRq3zbIxlrwXFC7oefIjTbucY34lrv92K7bqVf28GeUJ7HlfvhZhmCXdsScG8yRuk9YKkNkldU3/ahMCQnJSUEs9WB947sispW5w7RVjV4pmTug5XMwwbqiNEky+1Fr5N5zkR2cRy5iKst3/EbBhRPdbJMf92dFg2am6OvrJ+CbupQsRhwymC/bcnJblpL/XxZy/Cgul/fBeDgkjguFWE2zFW373RGTw0cfD/TaUoMeYaBvjdI4aAHeFvYl9/evBt/ps7YzRAFWbCwEtG9vsdXWfEqQDv0z9bKT01Qa3T181xeM1eCgTNWa/gorhLa9S42J9QX0m0HvYicuMhlnadoveeZyEeJhfhMxgcPTRoEghTSsWr12loPld5DR1G5OsFv5NwtSYWDz/JNBc71teSW3MJzK//lUVpOQXirU82s6Fj2YX1nfBl1kXfDcWUzaL0ftCUuUwwbZbM8ig3NmADXx7/zRqf+/9I1/Lb2L3psdU2CDGOwmkmrtTSktwLYsJ4cNVYkoqt7JbsK8/lT6fH1QKNtbgHYxczj1kpY986ILUZ3E8dVIm9arCaKPzEdmTI="
